# Introduction to Tensor

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


## Creat tensor with tf.constant()

In [3]:
# Create tensor with tf.constant()
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scaler.ndim


0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
# Create a matric (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [10,7]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]])>

In [8]:
matrix.ndim

2

In [9]:
# create another matric
another_matric = tf.constant([[10,7],
                              [3,2],
                              [8,9]], dtype=tf.float16)

In [10]:
another_matric.ndim

2

## Create tensor with tf.Variable

In [14]:
# Create the same tensor with tf.Variable as above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [16]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [17]:
# unchangable_ tensor không thể thêm vì nó là constant
# sẽ báo lỗi khi thêm hoặc sửa
unchangable_tensor[0].assign(9)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating random tensors with tensorflow

In [21]:
# Create 2 random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_1